fix: Fix empty test
Because `main.c` file isn't generated
and therefore `main` function isn't linked.

Error message:

> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
> (.text+0x1b): undefined reference to `main'
> collect2: error: ld returned 1 exit status
> error: Test 'tests/edges/empty' output differs